on:
  pull_request:
    branches: [ "**" ]

jobs:
  pull_reuqest_checks:
    runs-on: ubuntu-latest
    name: A job to check the pull request
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
      - name: Run pre-commit checks
        run: |
          echo Base: ${ENV_GITHUB_BASE_REPO}:${ENV_GITHUB_TARGET_REF}
          echo Head: ${ENV_GITHUB_HEAD_REPO}:${ENV_GITHUB_SOURCE_REF}
          echo ${ENV_GITHUB_ACTING_USER}
        env:
          ENV_GITHUB_SOURCE_REF: ${{ github.event.pull_request.head.ref }}
          ENV_GITHUB_TARGET_REF: origin/${{ github.event.pull_request.base.ref }}
          ENV_GITHUB_ACTING_USER: ${{ github.actor }}
          ENV_GITHUB_HEAD_REPO: ${{ github.event.pull_request.head.repo.git_url }}
          ENV_GITHUB_BASE_REPO: ${{ github.event.pull_request.base.repo.git_url }}
          ENV_GITHUB_BASE_CLONE_URL: ${{ github.event.pull_request.base.repo.clone_url }}
          ENV_GITHUB_BASE_REFS_URL: ${{ github.event.pull_request.base.repo.git_refs_url }}
      - name: Check write-protection files in the pull request
        id: check-protected-files
        uses: maxshine/personal-continuous-integrations@admin-role
        with:
          acting-user: ${{ github.actor }}
          merge-ref: origin/${{ github.event.pull_request.base.ref }}
          head-ref: ${{ github.event.pull_request.head.ref }}
          include-filter: '^.github/.*$'
          forked-repository-url: ${{ github.event.pull_request.base.repo.clone_url }}
